require 'rake/testtask'

task :default => [:test_unit]

desc "Run basic tests"
Rake::TestTask.new("test_unit") do |t|
	t.libs << ["tests"]
	t.test_files = FileList['test*.rb']
	t.verbose = true
	t.warning = true
end
