require 'rake/testtask'

task :default => [:test_unit]

desc "Run basic tests"
Rake::TestTask.new("test_unit") do |t|
	t.libs << ["../lib","../tests/models"]
	t.test_files = FileList['test*.rb']
	t.verbose = false
	t.warning = false
end
